version: '3.8'


volumes:
  mydb:

services:
  db:
    image: mysql
    container_name: db
    ports:
      - "3306:3306"
    volumes:
      - mydb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: nosh_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
  migrate:
    image: your_dockerhub_username/nosh_now_apis:latest
    entrypoint: ["dotnet", "ef", "database", "update"]
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - .:/src
      - ~/.nuget/packages:/root/.nuget/packages
      - ~/.dotnet/tools:/root/.dotnet/tools
    working_dir: /app
    depends_on:
      - db
  api:
    ports:
      - "5000:80"
    image: ${DOCKER_USERNAME}/nosh_now_apis
    depends_on:
      - migrate
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ISSUER=${TOKEN_ISSUER}
      - AUDIENCE=${TOKEN_AUDIENCE}
      - KEY=${TOKEN_KEY}
